' ******************************************************************************
' swxJRNL.swj - journal recorded on 10/26/25 by Tiger
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "MASTER ASSY", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
'TIMING:  - Total time = 868ms
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0528996701119931953, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, -0.1964844889874033107, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03436116964863843853, -0.1738132017965490772, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.06045676584227794442, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.0528996701119931953, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, -0.06801386157256268661, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01511419146056948611, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.1511419146056948437, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.2871696377508202169, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.04534257438170846005, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, 1.286468206536028447, 1.476377516761544939, 0.5630996440690410054

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.6701219530427238169, 0.9268362401332979061, 1.385548896631462412, -0.4808151018967751766, -0.5965093964714347496, 0.6426456081770718365, 0.002302260909908669662, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.6701219530427238169, 0.9268362401332979061, 1.385548896631462412, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Probing_MASTER_ASSY-1@MASTER ASSY", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Dim TransformData() As Double
ReDim TransformData(0 To 15) As Double
TransformData(0) = 1
TransformData(1) = 0
TransformData(2) = 0
TransformData(3) = 0
TransformData(4) = 1
TransformData(5) = 0
TransformData(6) = 0
TransformData(7) = 0
TransformData(8) = 1
TransformData(9) = -0.03664608851787223842
TransformData(10) = -0.02258328521948578527
TransformData(11) = -0.04837990678820579954
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
Dim TransformDataVariant As Variant
TransformDataVariant = TransformData
Dim swMathUtil As Object
Set swMathUtil = swApp.GetMathUtility()
Dim swTransform As Object
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Dim swComp As Object
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(0.6368606641821088488, 0.8315568174120926415, 1.335917669483819736, -0.4808151018967751766, -0.5965093964714347496, 0.6426456081770718365, 0.001807743687551318073, 2, True, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(0.634818084414803252, 0.8047209645382054077, 1.33591766948387658, -0.4808151018967751766, -0.5965093964714347496, 0.6426456081770718365, 0.002045520380860820202, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.634818084414803252, 0.8047209645382054077, 1.33591766948387658, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(2.056441811651666285, 1.577948541701402974, 0.3022495953864563489, -0.4808151018967751766, -0.5965093964714347496, 0.6426456081770718365, 0.003681936685549475931, 2, True, 0, 0)
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.0528996701119931953, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.08312805303313217098, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, 0.1209135316845558888, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0.1511419146056948437, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.09824224449370165535, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.09824224449370165535, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02267128719085423003, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01511419146056948611, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, 0.01511419146056948611, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.01511419146056948611, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.007557095730284743053, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.007557095730284743053, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03779728661350228308, -0.03778547865142371093, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06185010536754918797, -0.07557095730284742185, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, -0.04534257438170846005, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.03022838292113897221, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01511419146056948611, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.007557095730284743053, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.02267128719085423003, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01511419146056948611, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 1.020924583195437663, 1.371718196061863182, 1.157892083894182633

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(0.634818084414803252, 0.8047209645382054077, 1.33591766948387658, -0.5869726250826196035, -0.7906870798053514671, 0.1740031012151929124, 0.006283054530791750553, 2, True, 1, 0)
boolstatus = Part.Extension.SelectByRay(2.056441811651666285, 1.577948541701402974, 0.3022495953864563489, -0.5869726250826196035, -0.7906870798053514671, 0.1740031012151929124, 0.006283054530791750553, 2, True, 1, 0)

' Create CoincidentMateFeatureData
Dim MateData As CoincidentMateFeatureData
Set MateData = Part.CreateMateData(0)

' Set the Entities To Mate
Dim EntitiesToMate(1) As Object
Set EntitiesToMate(0) = Part.SelectionManager.GetSelectedObject6(1, -1)
Set EntitiesToMate(1) = Part.SelectionManager.GetSelectedObject6(2, -1)
Dim EntitiesToMateVar As Variant
EntitiesToMateVar = EntitiesToMate
MateData.EntitiesToMate = (EntitiesToMateVar)

' Set the Mate Alignment
MateData.MateAlignment = 2

' Create the mate
Dim MateFeature As Feature
Set MateFeature = Part.CreateMate(MateData)
Part.ClearSelection2 True
Part.EditRebuild3

boolstatus = Part.Extension.SelectByRay(0.6498032819533818838, 1.018089701235851408, 1.353089308027136894, -0.5869726250826196035, -0.7906870798053514671, 0.1740031012151929124, 0.003453599510302750048, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.6498032819533818838, 1.018089701235851408, 1.353089308027136894, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Probing_MASTER_ASSY-1@MASTER ASSY", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
ReDim TransformData(0 To 15) As Double
TransformData(0) = 1
TransformData(1) = 0
TransformData(2) = 0
TransformData(3) = 0
TransformData(4) = 1
TransformData(5) = 0
TransformData(6) = 0
TransformData(7) = 0
TransformData(8) = 1
TransformData(9) = 0.07673315962568724724
TransformData(10) = -0.06510490004177123258
TransformData(11) = 0.1408651309743897961
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
TransformDataVariant = TransformData
Set swMathUtil = swApp.GetMathUtility()
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007557095730284743053, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.08312805303313217098, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, -0.1738132017965490772, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, -0.1133564359542711536, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, -0.1057993402239863906, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.03022838292113897221, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.007557095730284743053, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.01511419146056948611, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.01511419146056948611, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, -0.02267128719085423003, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.007557095730284743053, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.007557095730284743053, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01511419146056948611, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007557095730284743053, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01511419146056948611, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01511419146056948611, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03022838292113897221, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03778547865142371093, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.03022838292113897221, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01511419146056948611, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.02267128719085423003, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.0528996701119931953, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.03778547865142371093, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01511419146056948611, 0.7650110982926321412, 1.149857741207483741, 1.541444100772338288

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, 0.1057993402239863906, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01511419146056948611, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03022838292113897221, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.07557095730284742185, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.08312805303313217098, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0906851487634169201, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03778547865142371093, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01511419146056948611, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01511419146056948611, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01511419146056948611, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01511419146056948611, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.03022838292113897221, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.03022838292113897221, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.04534257438170846005, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.03022838292113897221, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.06801386157256268661, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.03778547865142371093, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04534257438170846005, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01511419146056948611, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01511419146056948611, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03778547865142371093, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06045676584227794442, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.07557095730284742185, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.06045676584227794442, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.07557095730284742185, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.04534257438170846005, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.02267128719085423003, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007557095730284743053, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007557095730284743053, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01511419146056948611, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.01511419146056948611, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, 0.03778547865142371093, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.02267128719085423003, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01511419146056948611, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007557095730284743053, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007557095730284743053, 0.7529221778896726391, 1.061498617415963963, 1.536455643069132293

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.1435848188754101085, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.2342699676388270147, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.1360277231451253732, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.0528996701119931953, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.06045676584227794442, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0528996701119931953, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01511419146056948611, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.03022838292113897221, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06045676584227794442, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.04534257438170846005, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03778547865142371093, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.03778547865142371093, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.0528996701119931953, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.03022838292113897221, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02267128719085423003, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02267128719085423003, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.03778547865142371093, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.0906851487634169201, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, -0.1435848188754101085, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.06801386157256268661, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.08312805303313217098, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.0906851487634169201, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.06045676584227794442, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01511419146056948611, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.03022838292113897221, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.03778547865142371093, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.07557095730284742185, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.02267128719085423003, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.03778547865142371093, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01511419146056948611, 1.575429972831614123, 1.578510670713328068, 1.451748753373408363

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007557095730284743053, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.01511419146056948611, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02748893571891075291, -0.03778547865142371093, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, -0.03778547865142371093, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, -0.04534257438170846005, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02748893571891075291, -0.0528996701119931953, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02748893571891075291, -0.06045676584227794442, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04466952054322997218, -0.0906851487634169201, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, -0.08312805303313217098, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, -0.0906851487634169201, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03436116964863843853, -0.2267128719085423072, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.1964844889874033107, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.07557095730284742185, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01511419146056948611, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.0528996701119931953, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.06801386157256268661, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.03778547865142371093, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.04534257438170846005, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, -0.06045676584227794442, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05154175447295766127, -0.07557095730284742185, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.0528996701119931953, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.01511419146056948611, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.007557095730284743053, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.03778547865142371093, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.04534257438170846005, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04123340357836613457, -0.2871696377508202169, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03779728661350228308, -0.3173980206719592134, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.1435848188754101085, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.04534257438170846005, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.04534257438170846005, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.06045676584227794442, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.01511419146056948611, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, -0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04810563750809381672, -0.01511419146056948611, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05841398840268535037, 0, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05841398840268535037, 0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.08246680715673226914, 0.06045676584227794442, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05154175447295766127, 0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06528622233241303252, 0.01511419146056948611, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07559457322700456616, 0.03778547865142371093, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05841398840268535037, 0.04534257438170846005, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03779728661350228308, 0.04534257438170846005, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007557095730284743053, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04810563750809381672, 0.1889273932571185755, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.1738132017965490772, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.1133564359542711536, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.1511419146056948437, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.1435848188754101085, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.1511419146056948437, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.1057993402239863906, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02267128719085423003, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, 1.367266588681999906, 1.301885161220184273, 1.5235990985661374

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, -0.128470627414840638
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.2267128719085423072
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, -0.1209135316845558888
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, -0.1360277231451253732
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, -0.09824224449370165535
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, -0.166256106066264342
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, -0.3551834993233829452
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, -0.1964844889874033107
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.06045676584227794442
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1133564359542711536
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1209135316845558888
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.04534257438170846005

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, -0.0528996701119931953, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.09824224449370165535, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.06045676584227794442, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02267128719085423003, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03022838292113897221, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06045676584227794442, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04534257438170846005, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0528996701119931953, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.06045676584227794442, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02267128719085423003, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.03022838292113897221, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.03022838292113897221, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.06801386157256268661, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.06045676584227794442, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.03022838292113897221, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01511419146056948611, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01511419146056948611, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.03022838292113897221, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.03022838292113897221, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01511419146056948611, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007557095730284743053, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02267128719085423003, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.1057993402239863906, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.128470627414840638, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0906851487634169201, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03778547865142371093, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0528996701119931953, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04534257438170846005, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04534257438170846005, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02267128719085423003, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06045676584227794442, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.08312805303313217098, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.08312805303313217098, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.0906851487634169201, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.08312805303313217098, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.04534257438170846005, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.03778547865142371093, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.06045676584227794442, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.04534257438170846005, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.7639310549188564892, 0.8413929070807668609, 1.557212929822640035

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.7377825300970357603, 0.8618583375528743318, 1.540559172776283958, 0.627252899429019295, -0.1348701036036757672, -0.7670487959131560007, 0.003876659063428209481, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.7377825300970357603, 0.8618583375528743318, 1.540559172776283958, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Probing_MASTER_ASSY-1@MASTER ASSY", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
ReDim TransformData(0 To 15) As Double
TransformData(0) = 1
TransformData(1) = 0
TransformData(2) = 0
TransformData(3) = 0
TransformData(4) = 1
TransformData(5) = 0
TransformData(6) = 0
TransformData(7) = 0
TransformData(8) = 1
TransformData(9) = 0.4934247788801637835
TransformData(10) = 0.4543703908635809419
TransformData(11) = 0.3902747396726773399
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
TransformDataVariant = TransformData
Set swMathUtil = swApp.GetMathUtility()
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007557095730284743053
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.02267128719085423003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, -0.01511419146056948611
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.07559457322700456616, -0.0906851487634169201
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.09964739198105147799, -0.1511419146056948437
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05497787143782150582, -0.0906851487634169201
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04810563750809381672, -0.07557095730284742185
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05497787143782150582, -0.08312805303313217098
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05154175447295766127, -0.09824224449370165535
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, -0.0528996701119931953
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007557095730284743053
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, -0.01511419146056948611
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, 0.007557095730284743053
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, 0.02267128719085423003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05841398840268535037, 0.007557095730284743053
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, 0.01511419146056948611
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, 0.01511419146056948611
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, 0.02267128719085423003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04466952054322997218, 0.07557095730284742185
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, 0.09824224449370165535
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.04534257438170846005
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.09824224449370165535
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.07557095730284742185

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0.03022838292113897221
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03436116964863843853, 0.03778547865142371093
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04466952054322997218, 0.02267128719085423003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.06185010536754918797, 0.03022838292113897221
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04810563750809381672, 0.03022838292113897221
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.02267128719085423003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, -0.0528996701119931953
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03436116964863843853, -0.06801386157256268661
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.02267128719085423003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0528996701119931953
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.128470627414840638
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, -0.166256106066264342
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, -0.06801386157256268661
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, -0.04534257438170846005
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05154175447295766127, -0.07557095730284742185
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03779728661350228308, -0.0528996701119931953
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, -0.03778547865142371093
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, -0.02267128719085423003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, -0.01511419146056948611
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.01511419146056948611

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01511419146056948611
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, -0.01511419146056948611
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.06528622233241303252, -0.007557095730284743053
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.09621127501618763345, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.06528622233241303252, 0.02267128719085423003
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04810563750809381672, 0.03022838292113897221
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.007557095730284743053

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, 0.03778547865142371093, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03436116964863843853, 0.04534257438170846005, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007557095730284743053, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, 0.01511419146056948611, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04810563750809381672, 0.03778547865142371093, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05497787143782150582, 0.04534257438170846005, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07215845626214072162, 0.03778547865142371093, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06528622233241303252, 0.02267128719085423003, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0927751580513237889, 0.02267128719085423003, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1168279768053707007, 0.02267128719085423003, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07903069019186842459, 0.007557095730284743053, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, 0.007557095730284743053, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04466952054322997218, 0, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04810563750809381672, 0, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04466952054322997218, -0.007557095730284743053, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03436116964863843853, -0.02267128719085423003, 1.567138322989753974, 1.377036636285083659, 1.557492781814119098

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(1.165023826029795373, 1.377739317561982091, 1.806322315944555612, 0.1051558428596438555, -0.09551251547117409202, -0.9898583777999995226, 0.004086388229291443297, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 1.165023826029795373, 1.377739317561982091, 1.806322315944555612, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Probing_MASTER_ASSY-1@MASTER ASSY", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
ReDim TransformData(0 To 15) As Double
TransformData(0) = 1
TransformData(1) = 0
TransformData(2) = 0
TransformData(3) = 0
TransformData(4) = 1
TransformData(5) = 0
TransformData(6) = 0
TransformData(7) = 0
TransformData(8) = 1
TransformData(9) = 0.613213360429645693
TransformData(10) = 0.4174495082522370892
TransformData(11) = 0.4065628026835255149
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
TransformDataVariant = TransformData
Set swMathUtil = swApp.GetMathUtility()
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
Part.ClearSelection2 True
'TIMING:  - Total time = 2ms
Part.EditUndo2 1
'TIMING:  - Total time = 2ms
Part.EditUndo2 1
'TIMING:  - Total time = 2ms
Part.EditUndo2 1
Part.EditUndo2 1
'TIMING:  - Total time = 0ms
Part.EditUndo2 1
boolstatus = Part.Extension.SelectByRay(0.6751043613293177259, 0.9740650124649050667, 1.386426069995081889, -0.4808151018967751766, -0.5965093964714347496, 0.6426456081770718365, 0.003349007661191452916, 1, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(0.6746633066992444583, 0.9809891654363696034, 1.386096081391372081, -0.4808151018967751766, -0.5965093964714347496, 0.6426456081770718365, 0.005787085238538830154, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.6746633066992444583, 0.9809891654363696034, 1.386096081391372081, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Probing_MASTER_ASSY-1@MASTER ASSY", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
ReDim TransformData(0 To 15) As Double
TransformData(0) = 1
TransformData(1) = 0
TransformData(2) = 0
TransformData(3) = 0
TransformData(4) = 1
TransformData(5) = 0
TransformData(6) = 0
TransformData(7) = 0
TransformData(8) = 1
TransformData(9) = 0.2931711451006452362
TransformData(10) = -0.5611582427938003326
TransformData(11) = -0.3015270753639740509
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
TransformDataVariant = TransformData
Set swMathUtil = swApp.GetMathUtility()
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
boolstatus = Part.Extension.SelectByRay(0.9731312020112454775, 0.5645358610551056699, 1.08819778277165824, -0.4808151018967751766, -0.5965093964714347496, 0.6426456081770718365, 0.002497717624179981565, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.9731312020112454775, 0.5645358610551056699, 1.08819778277165824, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Probing_MASTER_ASSY-1@MASTER ASSY", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
ReDim TransformData(0 To 15) As Double
TransformData(0) = 1
TransformData(1) = 0
TransformData(2) = 0
TransformData(3) = 0
TransformData(4) = 1
TransformData(5) = 0
TransformData(6) = 0
TransformData(7) = 0
TransformData(8) = 1
TransformData(9) = -0.1975118969952409653
TransformData(10) = -0.2958793050165420824
TransformData(11) = -0.4224124230980469963
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
TransformDataVariant = TransformData
Set swMathUtil = swApp.GetMathUtility()
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.02267128719085423003, 1.348795923171678623, 1.405217288900416861, 0.190880756967032994
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.007557095730284743053, 1.348795923171678623, 1.405217288900416861, 0.190880756967032994
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06185010536754918797, 0, 1.348795923171678623, 1.405217288900416861, 0.190880756967032994
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05841398840268535037, 0, 1.348795923171678623, 1.405217288900416861, 0.190880756967032994
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04810563750809381672, -0.007557095730284743053, 1.348795923171678623, 1.405217288900416861, 0.190880756967032994
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, 0, 1.348795923171678623, 1.405217288900416861, 0.190880756967032994
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, 0, 1.348795923171678623, 1.405217288900416861, 0.190880756967032994
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, 1.348795923171678623, 1.405217288900416861, 0.190880756967032994

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.4727564422792056575, 0.679958149023121905, 0.9632896714501839597, -0.5452155016812613164, -0.3606499241255352595, 0.7567507442709895393, 0.002973331016002233023, 1, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(0.4704136634268820671, 0.6702017344319699532, 0.9618851531740801875, -0.5452155016812613164, -0.3606499241255352595, 0.7567507442709895393, 0.002973331016002233023, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("Line63@Sketch4@Chassis-1@MASTER ASSY/BaseplateV2-1@Chassis", "EXTSKETCHSEGMENT", 0, 0.4630646631360377796, 0, True, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05841398840268535037, 0.1435848188754101085, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07903069019186842459, 0.3249551164022439487, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.0528996701119931953, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.04534257438170846005, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.03778547865142371093, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007557095730284743053, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01511419146056948611, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01511419146056948611, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007557095730284743053, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007557095730284743053, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.03778547865142371093, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.07557095730284742185, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.06801386157256268661, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0528996701119931953, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.07557095730284742185, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.06801386157256268661, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.0528996701119931953, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.04534257438170846005, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02267128719085423003, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, 0.4773279868423969674, 0.8154600995888472426, 0.9651083407497367261

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(1.933535131102928517, 1.567627216918140221, 0.3022495953863426621, -0.6509483364930449545, -0.3375516500459647129, 0.6799449586313470739, 0.002973331016002233023, 2, True, 0, 0)

' Redraw
Part.GraphicsRedraw2
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.4743324734760634986, 0.5742688833538481807, 0.9656951531738665606, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Probing_MASTER_ASSY-1@MASTER ASSY", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
ReDim TransformData(0 To 15) As Double
TransformData(0) = 1
TransformData(1) = 0
TransformData(2) = 0
TransformData(3) = 0
TransformData(4) = 1
TransformData(5) = 0
TransformData(6) = 0
TransformData(7) = 0
TransformData(8) = 1
TransformData(9) = 0.07900332755261023354
TransformData(10) = -0.3676315585235933048
TransformData(11) = -0.1933100054815307389
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
TransformDataVariant = TransformData
Set swMathUtil = swApp.GetMathUtility()
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007557095730284743053, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.02267128719085423003, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03436116964863843853, 0.2342699676388270147, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04810563750809381672, 0.4307544566262303531, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04466952054322997218, 0.3854118822445218862, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.02267128719085423003, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007557095730284743053, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0528996701119931953, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0528996701119931953, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.07557095730284742185, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.08312805303313217098, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.2267128719085423072, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04123340357836613457, -0.5214396053896472871, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03779728661350228308, -0.3325122121325286839, 0.736932195510235033, 0.5360399980179124668, 1.188000143801730246

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
'TIMING:  - Total time = 3ms
Part.EditUndo2 1
'TIMING:  - Total time = 2ms
Part.EditUndo2 1
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
