' ******************************************************************************
' swxJRNL.swj - journal recorded on 02/01/26 by Tiger
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Linear Actuator Clamps (2026)", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02082276035519804377, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("Boss-Extrude2", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.FeatEdit
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("D1@Sketch2@Linear Actuator Clamps (2026).SLDPRT", "DIMENSION", -0.0247691475515324222, 0.1847850000000001436, 0.03291169769874893736, False, 0, Nothing, 0)
Dim myDimension As Object
Set myDimension = Part.Parameter("D1@Sketch2")
myDimension.SystemValue = 0.02
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Cut-Extrude3", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.FeatEdit
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("D4@Sketch7@Linear Actuator Clamps (2026).SLDPRT", "DIMENSION", 0.005456674796434940466, 0.1695700000000000263, 0.01025731269115688626, False, 0, Nothing, 0)
Set myDimension = Part.Parameter("D4@Sketch7")
myDimension.SystemValue = 0.006
boolstatus = Part.Extension.SelectByID2("D1@Sketch7@Linear Actuator Clamps (2026).SLDPRT", "DIMENSION", 0.01760841866934678701, 0.169570000000000165, 0.0306134186693468105, False, 0, Nothing, 0)
Set myDimension = Part.Parameter("D1@Sketch7")
myDimension.SystemValue = 0.006
boolstatus = Part.Extension.SelectByID2("D3@Sketch7@Linear Actuator Clamps (2026).SLDPRT", "DIMENSION", 0.02287159435952518249, 0.1695700000000001095, 0.02403444905662383002, False, 0, Nothing, 0)
Set myDimension = Part.Parameter("D3@Sketch7")
myDimension.SystemValue = 0.0055
boolstatus = Part.Extension.SelectByID2("D2@Sketch7@Linear Actuator Clamps (2026).SLDPRT", "DIMENSION", 0.005766273366445431869, 0.1695700000000001095, 0.02178985942404775694, False, 0, Nothing, 0)
Set myDimension = Part.Parameter("D2@Sketch7")
myDimension.SystemValue = 0.0055
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Save
Dim swErrors As Long
Dim swWarnings As Long
boolstatus = Part.Save3(1, swErrors, swWarnings)
boolstatus = Part.Extension.SelectByID2("Boss-Extrude3", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.FeatEdit
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Boss-Extrude3", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.FeatEdit
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Boss-Extrude1", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.FeatEdit
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("D3@Sketch1@Linear Actuator Clamps (2026).SLDPRT", "DIMENSION", 0.04644624668912200605, 0, 0.009437112204078872829, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("D2@Sketch1@Linear Actuator Clamps (2026).SLDPRT", "DIMENSION", 0.0004619749096852199255, 0, 0.003680194098770715044, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0.01169151886818756148, 0, 0.01142715796887675342, False, 0, Nothing, 0)
Dim myDisplayDim As Object
Set myDisplayDim = Part.AddDimension2(0.02149960156611997741, 0, 0.01427008049001659076)
Part.ClearSelection2 True
Set myDimension = Part.Parameter("D2@Sketch1")
myDimension.SystemValue = 0.018
boolstatus = Part.Extension.SelectByID2("Line4", "SKETCHSEGMENT", 0.003375970493853547305, 0, -0.01486987535166669344, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line2", "SKETCHSEGMENT", 0.005223870132594440885, 0, 0.01590476093967199342, True, 0, Nothing, 0)
Set myDisplayDim = Part.AddDimension2(0.03081017282285293535, 0, 0.006025605178711073567)
Part.ClearSelection2 True
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Point5", "SKETCHPOINT", 0.01448419828640853772, 0.001795000000000001456, 0, False, 0, Nothing, 0)
Set myDisplayDim = Part.AddDimension2(0.02384501264606034288, 0, -0.009965834002700482003)
Part.ClearSelection2 True
Part.SetPickMode
Part.SetPickMode
boolstatus = Part.Extension.SelectByID2("Point5", "SKETCHPOINT", 0.01448419828640853772, 0.001795000000000001456, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Sketch1", "SKETCHCONTOUR", 0.006361039141050378598, 0, -0.001579212565337977797, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Point8", "SKETCHPOINT", -0.01448419828640853772, 0.001795000000000001456, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SketchBoxSelect("-0.014534", "-0.017895", "0.000000", "-0.014463", "-0.018108", "0.000000")
boolstatus = Part.Extension.SelectByID2("Line2", "SKETCHSEGMENT", -0.0060767468889363907, 0, 0.01590476093967199342, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SketchBoxSelect("-0.009773", "-0.018961", "0.000000", "-0.009488", "-0.018890", "0.000000")
boolstatus = Part.Extension.SelectByID2("Unknown", "MANIPULATOR", -3.553653151425195666e-05, 0, 0.01732622220024191209, False, 0, Nothing, 0)
Part.EditDelete
Part.SketchManager.SketchConstraintsDel 1, "sgATMIDDLE"
boolstatus = Part.Extension.SelectByID2("Line2", "SKETCHSEGMENT", -0.00358918968293903129, 0, 0.0161179801287574774, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Point7", "SKETCHPOINT", -0.01000000000000000021, -0.01620500000000000065, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
Part.EditUndo2 1
boolstatus = Part.DeSelectByID("Point7", "SKETCHPOINT", -0.01000000000000000021, -0.01620500000000000065, 0)
Part.EditUndo2 1
Part.ClearSelection2 True
Part.EditUndo2 1
boolstatus = Part.Extension.SelectByID2("Point7", "SKETCHPOINT", -0.01000000000000000021, -0.01620500000000000065, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0.003091678241739573285, 0, -0.01408807165835323887, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Point5", "SKETCHPOINT", 0.01448419828640853772, 0.001795000000000001456, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0.01339727238087146111, 0, 0.002898390405457258734, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Point2", "SKETCHPOINT", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Point5", "SKETCHPOINT", 0.01448419828640853772, 0.001795000000000001456, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("D2@Sketch1@Linear Actuator Clamps (2026).SLDPRT", "DIMENSION", 0.02135745544006299734, 0, 0.01100071959070577851, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Point5", "SKETCHPOINT", 0.01448419828640853772, 0.001795000000000001456, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Unknown", "MANIPULATOR", -3.553653151425195666e-05, 0, 0.0009794177036878716491, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("D1@Sketch1@Linear Actuator Clamps (2026).SLDPRT", "DIMENSION", 0.02739866579748513609, 0, -0.003782477519221345841, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("D4@Sketch1@Linear Actuator Clamps (2026).SLDPRT", "DIMENSION", 0.07694312945014530891, 0, -0.009092203911954206685, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Point5", "SKETCHPOINT", 0.01448419828640853772, 0.001795000000000001456, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Point5", "SKETCHPOINT", 0.01427858954210711913, -0.00302256607670191562, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Point6", "SKETCHPOINT", 0.009985765355503663579, -0.01620500000000000065, 0, True, 0, Nothing, 0)
Set myDisplayDim = Part.AddDimension2(0.01418504621147928524, 0, 0.01301436161242912337)
Part.ClearSelection2 True
Set myDimension = Part.Parameter("D2@Sketch1")
myDimension.SystemValue = 0.018
boolstatus = Part.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0.002640506437634665415, 0, -0.01449603104013679616, False, 0, Nothing, 0)
boolstatus = Part.DeSelectByID("Arc1", "SKETCHSEGMENT", 0.002615497002484900354, 0.01435873254956692054, 0)
boolstatus = Part.Extension.SelectByID2("Line4", "SKETCHSEGMENT", 0.01025499011825559137, 0, -0.0140047740284838379, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line2", "SKETCHSEGMENT", 0.004482720231333281458, 0, 0.01964633126974411892, True, 0, Nothing, 0)
Set myDisplayDim = Part.AddDimension2(0.03088778460768001888, 0, 0.002820778620630147449)
Part.ClearSelection2 True
Part.ClearSelection2 True
Set myDimension = Part.Parameter("D3@Sketch1")
myDimension.SystemValue = 0.035
Part.SetPickMode
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Point5", "SKETCHPOINT", 0.01422354475758707583, -0.003271818993911071623, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Point5", "SKETCHPOINT", 0.01408879983007885368, -0.003810478230874718604, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0.01443067471730577478, 0, -0.0002495777022008746626, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Point5", "SKETCHPOINT", 0.01408879983007885368, -0.003810478230874718604, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Point6", "SKETCHPOINT", 0.009431446633602494703, -0.02040499999999999953, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Line2", "SKETCHSEGMENT", 0.001780806667241979779, 0, 0.02026040253431032889, False, 0, Nothing, 0)
Set myDisplayDim = Part.AddDimension2(0.0009211068968492941433, 0, 0.0334015275960270891)
Part.ClearSelection2 True
Set myDimension = Part.Parameter("D4@Sketch1")
myDimension.SystemValue = 0.02
Part.SetPickMode
Part.ClearSelection2 True
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode

' Redraw
Part.GraphicsRedraw2
boolstatus = Part.Extension.SelectByID2("Point5", "SKETCHPOINT", 0.01429872289575155435, -0.002925841511516029392, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line4", "SKETCHSEGMENT", 0.01443067471730577478, 0, -0.01474165954596327877, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", -0.01479911747604552297, 0, -0.0006180204609405950955, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0.006570562530858359285, 0, -0.01339070276391763487, False, 0, Nothing, 0)
Part.SetPickMode
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Point2", "SKETCHPOINT", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line4", "SKETCHSEGMENT", 0.007798705059990779231, 0, -0.01461884529305004093, True, 0, Nothing, 0)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04511598076959576209, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05205690088799511117, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05205690088799511117, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05552736094719478571, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05899782100639446025, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04858644082879543663, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04858644082879543663, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04164552071039608755, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04511598076959576209, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03470460059199673847, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0312341405327970674, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02429322041439771832, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01735230029599836923, -0.03867142187888968768, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.03867142187888968768, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, -0.0541399906304455697, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.100545696885113181, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.06960855938200143089, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0541399906304455697, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03093713750311174668, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01041138017759902189, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01041138017759902189, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01041138017759902189, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01388184023679869643, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01388184023679869643, -0.02320285312733381261, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01735230029599836923, -0.02320285312733381261, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01388184023679869643, -0.03867142187888968768, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01388184023679869643, -0.03867142187888968768, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01041138017759902189, -0.03867142187888968768, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.04640570625466762522, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.04640570625466762522, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.03093713750311174668, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03093713750311174668, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02320285312733381261, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03093713750311174668, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.01546856875155587334, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.02320285312733381261, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03093713750311174668, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.03093713750311174668, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03093713750311174668, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.03093713750311174668, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03093713750311174668, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02320285312733381261, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.03093713750311174668, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03867142187888968768, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.03867142187888968768, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03867142187888968768, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04640570625466762522, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03867142187888968768, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03093713750311174668, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02320285312733381261, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.01546856875155587334, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02320285312733381261, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.01785212660985280309, 0.3695699999999533247, 0.00438856897807227142

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("Cut-Extrude3", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.FeatEdit
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Part.EditUndo2 1
boolstatus = Part.Extension.SelectByID2("Cut-Extrude4", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.FeatEdit
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("D1@Sketch9@Linear Actuator Clamps (2026).SLDPRT", "DIMENSION", 0, 0.3456963398880359417, 0.04760167946422874663, False, 0, Nothing, 0)
Set myDimension = Part.Parameter("D1@Sketch9")
myDimension.SystemValue = 0.006
Part.SetPickMode
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06246828106559413479, -0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0798205813615925075, -0.04640570625466762522, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0798205813615925075, -0.03867142187888968768, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06593874112479380933, -0.01546856875155587334, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05899782100639446025, 0, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03817506065119641301, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02776368047359739286, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01388184023679869643, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02082276035519804377, 0, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01735230029599836923, 0, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01735230029599836923, 0, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01735230029599836923, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02082276035519804377, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02429322041439771832, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02776368047359739286, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0312341405327970674, 0.01546856875155587334, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02776368047359739286, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02082276035519804377, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02082276035519804377, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01735230029599836923, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01388184023679869643, 0, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01388184023679869643, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01388184023679869643, 0, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, -0.01499999999998635758, 0.3471150258693387891, 0.02756543148622656036

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02429322041439771832, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01041138017759902189, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01388184023679869643, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01041138017759902189, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01388184023679869643, -0.01546856875155587334, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01735230029599836923, -0.02320285312733381261, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01735230029599836923, -0.01546856875155587334, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01735230029599836923, -0.01546856875155587334, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02082276035519804377, -0.01546856875155587334, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01735230029599836923, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02429322041439771832, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02082276035519804377, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01735230029599836923, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01041138017759902189, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01041138017759902189, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01041138017759902189, -0.01546856875155587334, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01041138017759902189, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.00300000000009958967, 0.365485766788424371, 0.02317540758889435892

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("Cut-Extrude4[2]", "SOLIDBODY", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Cut-Extrude4[2]", "SOLIDBODY", 0, 0, 0, False, 0, Nothing, 0)
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 28
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Part.SaveToFile
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
boolstatus = Part.Extension.SelectByRay(-0.009999999999990905053, 0.3643927257401742281, 0.03186235381497226626, -0.4000360267793123259, -0.5150380749100240685, -0.7580942940502836125, 0.0003827939081965538561, 2, True, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, 0.1856228250186705009
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.06960855938200143089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.07734284375777937537
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.07734284375777937537
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0541399906304455697
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.01000000000001932676, 0.3623159581058530421, 0.0237424242152997067, 0.2389564023498198797, -0.4327118014730986228, -0.8692872566890283981, 0.0003827939081965538561, 2, True, 0, 0)
' MSGBOX
' Triangles: 862
' File Size: 43184 (Bytes)
' File Format: Binary
' Save C:\USERS\16467\DESKTOP\ROVER\SCIENCE-MODULE\2025\NPK PROBING\BIG PARTS + PROBE CASES\3D PRINTS\UPPERCLAMP20MM (FEB 1).STL?


' Save As
longstatus = Part.SaveAs3("C:\Users\16467\Desktop\Rover\Science-Module\2025\NPK Probing\Big Parts + Probe Cases\3D prints\UpperClamp20mm (Feb 1).STL", 0, 2)
' MSGBOX
' Save changes to Linear Actuator Clamps (2026)?

Part.ClearSelection2 True
swApp.ExitApp
End Sub
