' ******************************************************************************
' swxJRNL.swj - journal recorded on 02/01/26 by Tiger
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "LowerClampV1", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03817506065119641301, 0.3248399437826733349
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.06187427500622349336
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.2088256781460043066
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1082799812608911394
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1237485500124469867
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1314828343882249451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.1314828343882249451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.1392171187640028618
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.1778885406428925564
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02082276035519804377, -0.2397628156491160567
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.1392171187640028618
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.1314828343882249451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.1314828343882249451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.1237485500124469867
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.06960855938200143089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.06960855938200143089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02429322041439771832, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02082276035519804377, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02776368047359739286, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0312341405327970674, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0312341405327970674, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0312341405327970674, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03470460059199673847, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0312341405327970674, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02776368047359739286, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02776368047359739286, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02776368047359739286, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02429322041439771832, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02082276035519804377, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02082276035519804377, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.0541399906304455697
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02082276035519804377, -0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01735230029599836923, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.06187427500622349336
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.0541399906304455697
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.100545696885113181
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.06960855938200143089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.07734284375777937537
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.06187427500622349336
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.06187427500622349336
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02776368047359739286, -0.0541399906304455697
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02082276035519804377, -0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04511598076959576209, -0.100545696885113181
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03470460059199673847, -0.07734284375777937537
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03817506065119641301, -0.09281141250933525044
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03817506065119641301, -0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03470460059199673847, -0.07734284375777937537
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0312341405327970674, -0.06960855938200143089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0312341405327970674, -0.06960855938200143089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02776368047359739286, -0.06187427500622349336
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, -0.0541399906304455697
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02082276035519804377, -0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01735230029599836923, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("NoBottom", "CONFIGURATIONS", 0, 0, 0, False, 0, Nothing, 0)

' Open
Set Part = swApp.OpenDoc6("C:\Users\16467\Desktop\Rover\Science-Module\2025\NPK Probing\Big Parts + Probe Cases\Linear Actuator Clamps (2026).SLDPRT", 1, 0, "", longstatus, longwarnings)
boolstatus = Part.ShowConfiguration2("NoBottom")
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.1237485500124469867
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.06187427500622349336
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.0541399906304455697
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.07734284375777937537
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.07734284375777937537
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.07734284375777937537
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.07734284375777937537
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.06960855938200143089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, 0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.009999999999877218215, -0.01587023778620277881, 0.0285380976489477689, -0.5218829523541649307, -0.260819094660295292, -0.8121647516992376303, 0.0009309578321945119212, 2, True, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.146951403139780834
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.009999999999990905053, -0.01905804841501890223, 0.02768384574392257491, 0.2075643825085642658, -0.1529537176479357219, -0.966189519386085105, 0.0009309578321945119212, 2, True, 0, 0)
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 28
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "TestingActuatorEndBig", False, longstatus
Set Part = swApp.ActiveDoc

' Redraw
Part.GraphicsRedraw2
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04164552071039608755, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03817506065119641301, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03817506065119641301, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0312341405327970674, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02429322041439771832, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.06593874112479380933, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04164552071039608755, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04164552071039608755, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03817506065119641301, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03817506065119641301, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03817506065119641301, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02776368047359739286, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01735230029599836923, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "LowerClampV1", False, longstatus
Set Part = swApp.ActiveDoc

' Redraw
Part.GraphicsRedraw2
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02082276035519804377, 0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05899782100639446025, 0.4099170719162307241
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.1314828343882249451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.1314828343882249451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.1160142656366690561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.06187427500622349336
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01735230029599836923, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01735230029599836923, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02776368047359739286, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02429322041439771832, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02429322041439771832, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03470460059199673847, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0312341405327970674, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03470460059199673847, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02776368047359739286, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0312341405327970674, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02776368047359739286, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02429322041439771832, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02776368047359739286, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02082276035519804377, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01735230029599836923, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01735230029599836923, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01735230029599836923, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, -0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, -0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
' MSGBOX
' Triangles: 676
' File Size: 33884 (Bytes)
' File Format: Binary
' Save C:\USERS\16467\DESKTOP\ROVER\SCIENCE-MODULE\2025\NPK PROBING\BIG PARTS + PROBE CASES\3D PRINTS\BETTERLOWERCLAMPV1_NOBOTTOM.STL?


' Save As
longstatus = Part.SaveAs3("C:\Users\16467\Desktop\Rover\Science-Module\2025\NPK Probing\Big Parts + Probe Cases\3D prints\BETTERLowerClampV1_nobottom.STL", 0, 2)
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 28
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "TestingActuatorEndBig", False, longstatus
Set Part = swApp.ActiveDoc
swApp.ExitApp
End Sub
