' ******************************************************************************
' swxJRNL.swj - journal recorded on 11/15/25 by Tiger
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "LinearActuator Casing", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03470460059199673847, 0.135503867985388049
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.0677519339926940245
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0.1778488267308218074
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.2625387442216893796
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.1947868102289953274
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02540697524726025919
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.03387596699634701225
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.05081395049452051838
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.05081395049452051838
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0677519339926940245
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0762209257417807845
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0677519339926940245
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.05081395049452051838
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02540697524726025919
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02540697524726025919
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, -0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02429322041439771832, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01735230029599836923, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.03387596699634701225
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.02540697524726025919
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02540697524726025919
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02540697524726025919
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03387596699634701225
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02540697524726025919
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03387596699634701225
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02540697524726025919
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02540697524726025919
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01693798349817350613
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.008468991749086753063
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
swApp.ExitApp
End Sub
