' ******************************************************************************
' swxJRNL.swj - journal recorded on 02/01/26 by Tiger
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "SlidingPlate_AssemblyV3", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
'TIMING:  - Total time = 74ms
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02429322041439771832, 0.04640570625466762522, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02429322041439771832, 0.0541399906304455697, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02429322041439771832, 0.06960855938200143089, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01735230029599836923, 0.04640570625466762522, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01388184023679869643, 0.04640570625466762522, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01041138017759902189, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01388184023679869643, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01388184023679869643, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01388184023679869643, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01735230029599836923, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02082276035519804377, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01735230029599836923, 0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01041138017759902189, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01041138017759902189, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01041138017759902189, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01041138017759902189, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01041138017759902189, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.03867142187888968768, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.03093713750311174668, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.03093713750311174668, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.03093713750311174668, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0.03093713750311174668, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.03093713750311174668, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.03093713750311174668, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.03093713750311174668, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.03093713750311174668, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.02320285312733381261, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03093713750311174668, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01041138017759902189, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.00773428437577793667, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.6871721997071631449, 0.9873726436903211834, 1.291627939852503459

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1804639230783830484, 0.4021827875404527242, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03470460059199673847, 0.100545696885113181, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0312341405327970674, 0.06960855938200143089, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0312341405327970674, 0.04640570625466762522, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0312341405327970674, 0.03093713750311174668, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03470460059199673847, 0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03817506065119641301, 0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04511598076959576209, 0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04164552071039608755, 0.03093713750311174668, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03470460059199673847, 0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02429322041439771832, 0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01388184023679869643, 0, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, 0, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, -0.03867142187888968768, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03093713750311174668, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03093713750311174668, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03093713750311174668, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, -0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01041138017759902189, 0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01041138017759902189, 0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.02320285312733381261, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01041138017759902189, 0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006940920118399348214, 0.01546856875155587334, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003470460059199674107, 0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006940920118399348214, -0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, -0.00773428437577793667, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003470460059199674107, 0, 0.7207356099945627648, 1.101127850026955457, 1.352006373982646892

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.709668067032282579, 1.105052236816163713, 1.348684686636246965, -0.6703514981878981871, -0.73069114003711233, 0.1293032356459258292, 0.001144691660983925777, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("Unknown", "POINTREF", 0.7091506344536543383, 1.081076069727217037, 1.347987226608210465, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.7280827286634803386, 1.127295291011250811, 1.30316676897832906, -0.6703514981878981871, -0.73069114003711233, 0.1293032356459258292, 0.001144691660983925777, 1, True, 0, 0)
boolstatus = Part.Extension.SelectByRay(0.7100783017659182406, 1.108654399028409898, 1.305806559651628618, -0.6703514981878981871, -0.73069114003711233, 0.1293032356459258292, 2.428323096072364432e-05, 2, True, 0, 0)
boolstatus = Part.Extension.SelectByRay(0.7091680174898442601, 1.107707603511983052, 1.348077346119765707, -0.6703514981878981871, -0.73069114003711233, 0.1293032356459258292, 0.000117078823645919066, 1, True, 0, 0)
boolstatus = Part.Extension.SelectByRay(0.7093792769004494403, 0.8843161368453706928, 1.321909493907284627, -0.6703514981878981871, -0.73069114003711233, 0.1293032356459258292, 0.001449939364381610737, 2, True, 0, 0)
' MSGBOX
' Save changes to SlidingPlate_AssemblyV3?

Part.ClearSelection2 True
swApp.ExitApp
End Sub
