' ******************************************************************************
' swxJRNL.swj - journal recorded on 02/01/26 by Tiger
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Linear Actuator Clamps (2026)", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02429322041439771832, 0.06187427500622349336
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01388184023679869643, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.01264095315327296021, -0.03269356898732667105, 0.0418719008864911757, 0.1023611825267833481, 0.9398372409686047702, -0.325926600326268634, 0.001083580542739888625, 1, True, 0, 0)
boolstatus = Part.Extension.SelectByRay(-0.01302028590387749318, -0.03266511646637582089, 0.03989596449812893297, 0.1023611825267833481, 0.9398372409686047702, -0.325926600326268634, 0.001083580542739888625, 1, True, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01735230029599836923, 0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01388184023679869643, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.06960855938200143089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.1082799812608911394
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.100545696885113181
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.08507712813355731984
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.07734284375777937537
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.0541399906304455697
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0541399906304455697
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02776368047359739286, 0.6728827406926806143
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01735230029599836923, 0.3480427969100071683
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.1392171187640028618
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03867142187888968768
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.04640570625466762522
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03093713750311174668
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006940920118399348214, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02320285312733381261
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01041138017759902189, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006940920118399348214, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01546856875155587334
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003470460059199674107, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.00773428437577793667

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.ClearSelection2 True
swApp.ExitApp
End Sub
