' ******************************************************************************
' swxJRNL.swj - journal recorded on 11/23/25 by Tiger
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Main NPK Assembly", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
boolstatus = Part.Extension.SelectByID2("Model #2", "CONFIGURATIONS", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.ShowConfiguration2("Model #2")
boolstatus = Part.Extension.SelectByRay(-0.2160371094117863322, 0.2174356221264304168, 0.06370703517717402065, -0.4692148035644019277, -0.3265109249523411861, 0.820504773906152618, 0.0007387732858134709495, 2, False, 0, 0)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02081181253166744516, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02081181253166744516, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02081181253166744516, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02081181253166744516, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01734317710972287443, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02428044795361202282, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01387454168777829677, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01734317710972287443, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01734317710972287443, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01734317710972287443, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01734317710972287443, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01734317710972287443, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02428044795361202282, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01734317710972287443, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01387454168777829677, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, -0.01501102291817651979, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01734317710972287443, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007505511459088259896, -0.2706008776348198808, 0.2430275686549805414, 0.04929890948471893353

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0.007505511459088259896, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0.007505511459088259896, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0.007505511459088259896, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0.007505511459088259896, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0.007505511459088259896, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0.007505511459088259896, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0.007505511459088259896, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0.007505511459088259896, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01040590626583372258, 0.007505511459088259896, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006937270843889148386, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0.007505511459088259896, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003468635421944574193, 0, -0.266680717651006205, 0.195079265491813203, 0.06786636639230891888

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003468635421944574193, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01040590626583372258, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01040590626583372258, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01387454168777829677, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01387454168777829677, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01387454168777829677, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02081181253166744516, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02081181253166744516, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02428044795361202282, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02774908337555659354, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02428044795361202282, -0.01501102291817651979, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02774908337555659354, -0.02251653437726477969, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02774908337555659354, -0.01501102291817651979, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03121771879750117121, -0.01501102291817651979, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03121771879750117121, -0.01501102291817651979, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02774908337555659354, -0.01501102291817651979, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03121771879750117121, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03121771879750117121, -0.01501102291817651979, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02774908337555659354, -0.01501102291817651979, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02428044795361202282, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02081181253166744516, -0.02251653437726477969, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02081181253166744516, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02081181253166744516, -0.01501102291817651979, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02081181253166744516, -0.01501102291817651979, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02081181253166744516, -0.01501102291817651979, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02081181253166744516, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01734317710972287443, -0.01501102291817651979, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01734317710972287443, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01387454168777829677, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01040590626583372258, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01040590626583372258, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01040590626583372258, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003468635421944574193, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003468635421944574193, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003468635421944574193, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, -0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01040590626583372258, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003468635421944574193, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003468635421944574193, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006937270843889148386, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003468635421944574193, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003468635421944574193, 0, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007505511459088259896, -0.230285995540732813, 0.2880921936456957155, 0.05332849402532247041

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.239561213312171617, 0.2654890943026231298, 0.04610784219863717226, -0.08563307157015292992, -0.2397785715302868659, 0.9670435428088832719, 0.0008689386623434816907, 2, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(-0.2519331967745586098, 0.1704185186149516085, 0.0585567398877060441, -0.08563307157015292992, -0.2397785715302868659, 0.9670435428088832719, 0.0007212190897450897718, 1, False, 0, 0)

' Named View
Part.ShowNamedView2 "*Top", 5
Part.ViewZoomtofit2
Part.ClearSelection2 True

' Named View
Part.ShowNamedView2 "*Right", 4
Part.ViewZoomtofit2
swApp.ExitApp
End Sub
